apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
# Type of secret: Defines how it is handled by kubernetes
type: Opaque
# Data is base 64 encoded
data:
  #AUTH0_DOMAIN: dev-c7fbbyt.eu.auth0.com
  #AUTH0_AUDIENCE: https://casino-api/
  #MONGO_INITDB_ROOT_DATABASE: users
  #MONGO_INITDB_TEST_DATABASE: users
  #MONGO_INITDB_ROOT_HOST: ccuser.5orfj.mongodb.net
  #MONGO_INITDB_ROOT_USERNAME: admin
  #MONGO_INITDB_ROOT_PASSWORD: sUBj2oZ99bONNBcR
  AUTH0_DOMAIN: ZGV2LWM3ZmJieXQuZXUuYXV0aDAuY29tCg==
  AUTH0_AUDIENCE: aHR0cHM6Ly9jYXNpbm8tYXBpLwo=
  MONGO_INITDB_ROOT_DATABASE: dXNlcnMK
  MONGO_INITDB_TEST_DATABASE: dXNlcnMK
  MONGO_INITDB_ROOT_HOST: Y2N1c2VyLjVvcmZqLm1vbmdvZGIubmV0Cg==
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4K
  MONGO_INITDB_ROOT_PASSWORD: c1VCajJvWjk5Yk9OTkJjUgo=