name: test_and_build
on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  test_and_build:
    uses: JulianTeschner/go_test_build_action/.github/workflows/test_build.yml@main
    with:
      COVERAGE_PERCENTAGE: 75
      WORKING_DIR: ./userService
      GO_VERSION: 1.17.x
      OS_VERSION: ubuntu-latest
      IMAGE_NAME: user_service
      VERSION: 1
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
